### ISSUE TITLE
Better search

### ISSUE THREAD

**Issue by ewels** [nf-core/website#1024]
It would be great to use a search tool that scrapes the website, to easily get pages rendered using different methods.

One tool that looks quite promising that @Emiller88 found is _algolia_: https://www.algolia.com/developers/search-api-php/

**Comment by Emiller88** [comment]
I think this is what we want https://pagefind.app/

**Comment by mashehu** [comment]
> I think this is what we want https://pagefind.app/

Almost. Didn't get the weights right for my taste. 

But there is something else on the way #1981

**Comment by Emiller88** [comment]
Looks great! Just some form of search 😆
 
> Almost. Didn't get the weights right for my taste.

What do you mean by weights?

**Comment by mashehu** [comment]
> What do you mean by weights?

The relevance of each result, which decides the order by which they come up.
