### ISSUE TITLE
Have link to pdf exports for hackmd.io presentations

### ISSUE THREAD

**Issue by maxulysse** [nf-core/website#1034]
Just need to add `?print-pdf` before the final `#` to allow printing in pdf format (so basically save as a pdf).
Might be good to have that on all our hackmd.io presentations

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Furentsu** [comment]
Where exactly should I make this change?
