### ISSUE TITLE
Add guidance using Gitpod

### ISSUE THREAD

**Issue by mahesh-panchal** [nf-core/website#1055]
**Is your feature request related to a problem? Please describe.**
Gitpod environments will soon be enabled across all nf-core repos. It would be nice to have a how to use page

**Describe the solution you'd like**
A page showing how to use Gitpod on nf-core
- basics of what Gitpod is, and what the nf-core gitpod environment contains.
- How to test a module with pytest in Gitpod
- How to do a code review
- How to develop the tools package
- How to develop for the website
- How to update the Gitpod environment

**Describe alternatives you've considered**

**Additional context**

**Comment by mashehu** [comment]
Good idea. I was also proposing to have a bytesize talk about it.

**Comment by mahesh-panchal** [comment]
That would be useful too.

**Comment by chriswyatt1** [comment]
I starting writing a section on the nf-core webpage (in Developers/Using_gitpod_for_development) or something along these lines. I will assign myself

**Comment by mahesh-panchal** [comment]
Just to reiterate what I wrote in a chat.
It's a better idea to separate each bullet point as their own guide, except for the Gitpod summary.
The nf-core website has a different Gitpod environment to the rest of the nf-core repositories. 
The gitpod dockerfile for the Gitpod environment propogated to the rest of the nf-core repositories is defined here: https://github.com/nf-core/tools/blob/dev/nf_core/gitpod/gitpod.Dockerfile

A module test is run on Gitpod in the modules repository using:
```
PROFILE=docker pytest --tag <MODULE> --symlink --keep-workflow-wd --git-aware
```

**Comment by chriswyatt1** [comment]
Ok, I have separated out all the sections. I think it looks much clearer now. Definitely still needs a bit of work!
