### ISSUE TITLE
Write step-by-step guide for building pipelines

### ISSUE THREAD

**Issue by priyanka-surana** [nf-core/website#1077]
The goal is to add detailed steps on adding pipeline based on nf-core guidelines.

Some suggestions from @drpatelh:
> All the way from creating a pipeline -> adding nf-core/modules or local modules -> etc You have been through this process and know exactly what we need to add.
> We can also look at some of the questions asked on [#dsl2-transition](https://nfcore.slack.com/archives/C027CM7P08M) to find common things that aren't documented yet

**Is your feature request related to a problem? Please describe.**
The feature request is related to lack of documentation for building pipelines.

**Describe the solution you'd like**
A clear detailed step by step guide is needed especially keeping new users in mind.

**Describe alternatives you've considered**
Letting people figure it out painfully or maybe via Slack. (:sarcasm:)

**Additional context**
Working document: https://docs.google.com/document/d/1ucXxJTjeYMvU4lUwmkI5bN6mFCQ9sbTfWIAL7LPGSlc/edit?usp=sharing

**Comment by sateeshperi** [comment]
how much overlap would you think this issue would have with [this one](https://github.com/nf-core/nf-co.re/issues/887) ?

**Comment by priyanka-surana** [comment]
@sateeshperi I guess people in `group 3` and `group 2` are working on similar topics. Might be best to collaborate, so we don't replicate each other.

**Comment by gregorysprenger** [comment]
@FranBonath [Creating pipelines with nf-core](https://nf-co.re/docs/contributing/tutorials/creating_with_nf_core) is a guide on building a pipeline using DSL2. It was last updated in October 2022. Is this guide sufficient to close this issue?
