### ISSUE TITLE
Make some form of discipline specific collection or spotlight section/age

### ISSUE THREAD

**Issue by jfy133** [nf-core/website#1153]
**Is your feature request related to a problem? Please describe.**
Sometimes we have people asking for what pipelines can use for XYZ type of data or discipline.

**Describe the solution you'd like**
It would be cool to have a 'collection' or 'spotlight' thing to showcase related pipelines in a obvious/clear manner (versus tagging filtering, which is somewhat hidden,

e.g.: 
- metagenomics: eager, mag, bacass (taxprofiler, funcscan)
- genomics: sarek, eager
- rna: rnaseq, ampliseq, smrna-seq
- protemics: diaproteomics, proteomicslifq

Ideas:

- A carosel defined by special tags that is displayed at the top of the pieplines page or homepage

**Describe alternatives you've considered**
NA

**Additional context**
See thread here: https://nfcore.slack.com/archives/CE6SDEDAA/p1651818516719209?thread_ts=1651814727.496029&cid=CE6SDEDAA

**Comment by mashehu** [comment]
Solved with special interest groups
