### ISSUE TITLE
Add section for support

### ISSUE THREAD

**Issue by ewels** [nf-core/website#1246]
We now have a few people who support us by giving us free stuff. The latest is HackMD ([logos page](https://hackmd.io/@hackmd/press-kit)), but also Gitpod and others?

Would be nice to have a place on the website to feature these lovely folks. We have financial support listed on the "About Us" page but I wonder if we should extend this into multiple pages and add a bit more content or something. Open to ideas.

**Comment by sofiahag** [comment]
Maybe just create a separate page for this, and add it to the dropdown, e.g. "Financial Support":

![Skärmavbild 2023-03-29 kl  13 35 31](https://user-images.githubusercontent.com/37932118/228524831-1cb6917f-eba1-409a-b4f8-3a9886718454.png)

![Skärmavbild 2023-03-29 kl  13 40 54](https://user-images.githubusercontent.com/37932118/228524844-48a92d1c-71dd-435e-a3bc-9c0870931cb3.png)

**Comment by mashehu** [comment]
I think having it in the "about nf-core" page is fine for now
