### ISSUE TITLE
Create new subsections for pipeline documentation

### ISSUE THREAD

**Issue by christopher-hakkaart** [nf-core/website#1252]
**Create new subsections for pipeline documentation**

Some developers would like to have fully featured documentation for their pipelines, not just usage and output. Overall aim is to allow more flexibility in documentation to allow expanded support. 

It would be nice to add the following to the site:
- Sticky tab bar for pipeline page
- Reduce Usage + Output
- Under Docs, have new left sidebar
- Auto-detect markdown files (nested), e.g. FAQ, tutorials
- Use front-matter for priority etc. (see nf-co.re/docs)
- Keep template docs as barebones as possible (move to main nf-core docs)

**Comment by mashehu** [comment]
Done, see https://nf-co.re/crisprseq/2.0.0/docs/usage/
