### ISSUE TITLE
Write governance document

### ISSUE THREAD

**Issue by christopher-hakkaart** [nf-core/website#1254]
**Write governance document**

Write governance document for the nf-core website. Will need to be a new section under about (or other)

Required:
- [ ] Explanation
- [ ] Diagram?
- [ ] Groups names + descriptions
- [ ] [List groups members](https://github.com/nf-core/nf-co.re/issues/1249)

Examples
- [Meritocratic Governance Model](http://oss-watch.ac.uk/resources/meritocraticgovernancemodel)
- [Benevolent Dictator Governance Model](http://oss-watch.ac.uk/resources/benevolentdictatorgovernancemodel)
- [How To Draw Up A Governance Document](http://oss-watch.ac.uk/resources/governancemodels#how-to-draw-up-a-governance-document)
- scverse [teams](https://scverse.org/people/) and [roles](https://scverse.org/about/roles/)

**Comment by mashehu** [comment]
https://nf-co.re/governance
