### ISSUE TITLE
Change the styling/location of the Edit button for pages

### ISSUE THREAD

**Issue by abhi18av** [nf-core/website#1357]
During the hackathon we did a lot of proof-reading of the content and the ability to `Edit` a page is great, however it is not discoverable by first-time readers.

The `Edit` button is at the top-right of the page and blends in to the background (default green color) and isn't noticeable once the reader scrolls down i.e. the area where the user is likely to see typos etc.

<img width="406" alt="image" src="https://user-images.githubusercontent.com/12799326/195047442-8685676e-9bd9-4be3-b3a4-b128e47894a0.png">

To alleviate this we could either 
1. Make the `Edit` button darker (short term fix)
2. Relocate the `Edit` button close to the index of the page, as shown below 

<img width="406" alt="Screenshot 2022-10-11 at 11 06 48 AM" src="https://user-images.githubusercontent.com/12799326/195048760-f413c56d-cf59-42e3-bdec-2e0fbc4b5bbe.png">

**Comment by mribeirodantas** [comment]
@mashehu What do you think?

**Comment by mashehu** [comment]
we could make it a bit darker still, but I wouldn't add it to the ToC.

**Comment by sofiahag** [comment]
Maybe we can just change the opacity to 1? 

Like:

![Skärmavbild 2023-03-29 kl  13 27 39](https://user-images.githubusercontent.com/37932118/228521774-101cdd54-a72e-487b-80a3-299b1deee071.png)

**Comment by sofiahag** [comment]
Closing since PR closed.
