### ISSUE TITLE
DSL2 modules tutorial - pytest tags issue

### ISSUE THREAD

**Issue by JackCurragh** [nf-core/website#1369]
**Describe the bug**
Examples in tutorial swap from fgbio_fastqtobam to fgbio_bamtofastq in the [Run tests locally](https://nf-co.re/developers/tutorials/dsl2_modules_tutorial#run-tests-locally) section. 

**To Reproduce**

1. Go to ['Run tests locally'](https://nf-co.re/developers/tutorials/dsl2_modules_tutorial#run-tests-locally)
2. See error in code blocks 2,3 and 4 of this section

**Comment by LouisLeNezet** [comment]
Hi @gregorysprenger it's always good to connect issues and PRs, for example by adding a comment like "fixes issue #xxx". Read more about it [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

**Comment by gregorysprenger** [comment]
PR for this issue https://github.com/nf-core/nf-co.re/pull/1715
