### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by JRWallace** [nf-core/website#1445]
I am getting an Error 404 message here: https://nf-co.re//usage#samplesheet-input, which I was directed to via https://nf-co.re/nanoseq/3.0.0/parameters

**Comment by sofiahag** [comment]
This has been fixed for the latest release 3.1.0: https://nf-co.re/nanoseq/3.1.0/parameters

The link is supposed to be: https://nf-co.re/nanoseq/usage#samplesheet-input

Maybe we don't need to fix it for old releases?

**Comment by sofiahag** [comment]
Has been fixed!
