### ISSUE TITLE
refgenie problem

### ISSUE THREAD

**Issue by freedog8** [nf-core/website#1508]
**Describe the bug**
~/.nextflow/nf-core/refgenie_genomes.config was not automatically created after refgenie installation and initiation.

**Comment by mirpedrol** [comment]
Hello @freedog8, could you provide more information? What commands did you use? and which is your nf-core version? Thanks :)

**Comment by peterkilfeather** [comment]
Also getting this problem. 
System-wide nextflow install (v23.04.1.5866)
Conda nf-core (v2.7.2)

Installed ref genie from the instructions here: http://refgenie.databio.org/en/latest/
Pulled mm10/fasta successfully. No ~/.nextflow/nf-core/refgenie_genomes.config still.

**Comment by mirpedrol** [comment]
Have you initialized refgenie with `refgenie init -c $REFGENIE`? Did you set the environment variable `$REFGENIE` or provide a path manually?

**Comment by peterkilfeather** [comment]
I added `export REFGENIE=/refgenie/genome_config.yaml` to the bottom of my ~/.bashrc and then ran `refgenie init -c $REFGENIE`

**Comment by mirpedrol** [comment]
Sorry for asking too many questions, I can't reproduce the error, so it's a bit difficult to debug.
Could you please check the paths in these environment variables: $NXF_HOME and $NXF_REFGENIE_PATH
Thanks!

**Comment by peterkilfeather** [comment]
Neither variable exists for me. In the end I decided to just manually download the FASTA and GTF I need and specified them in the rnaseq nf-core command. If I have time, I will try a fresh reinstall of nextflow/nf-core/refgenie. Thank you for your help!
