### ISSUE TITLE
Update guide to writing an institutional profile

### ISSUE THREAD

**Issue by sofstam** [nf-core/website#1619]
The content of the https://github.com/nf-core/nf-co.re/tree/master/public_html/assets/img/contributors-white is not the same as the content of the https://github.com/nf-core/nf-co.re/tree/master/public_html/assets/img/contributors-colour.

**Comment by sofiahag** [comment]
I'm guessing these logos have not been rendered in white because it would mess up the logo? 

<img width="785" alt="Skärmavbild 2023-10-16 kl  21 42 14" src="https://github.com/nf-core/website/assets/37932118/193b8825-44e2-40b3-8296-004354a60c32">

**Comment by sofiahag** [comment]
I checked with @mashehu, and this should be fine, since the files that differ are not institutions.
