### ISSUE TITLE
The pipeline sidebar isn't being fully displayed and is non-scrollable

### ISSUE THREAD

**Issue by sofiahag** [nf-core/website#1697]
When I click on any pipeline page, the sidebar isn't being fully displayed.

To reproduce, click on any pipeline page with a longer sidebar, e.g. https://nf-co.re/sarek.

It would be nice to have a scrollbar for smaller screens?

<img width="380" alt="Skärmavbild 2023-03-27 kl  14 17 55" src="https://user-images.githubusercontent.com/37932118/227942806-18ff3263-67df-4b35-81b8-7fef80d8e691.png">

**Comment by sofiahag** [comment]
Ah, I think I probably just didn't scroll down far enough, it gets stuck in the middle,  to wait for the main page to reach the bottom:

![screen_rec](https://github.com/nf-core/website/assets/37932118/b6002dec-f14a-4db4-83ab-82d73b81ee01)

**Comment by sofiahag** [comment]
Probably not an issue, I'll close it!

**Comment by mashehu** [comment]
thanks for digging this one up. I added now a max-height + overflow in #1872

**Comment by sofiahag** [comment]
Great, thank you! 🙏🏻
