### ISSUE TITLE
add missing intro bits to bytesize transcripts

### ISSUE THREAD

**Issue by FranBonath** [nf-core/website#1707]
The following text is missing from https://nf-co.re/events/2021/bytesize-23-nf-core-hic :

"(host) Hi everyone. Happy to have you here again for our bytesize talk today. We are joined today by Nicolas Servant, who is based at the Institute Curie in Paris, France. He is talking to us about the nf-core/hic pipeline. If you have any questions for Nicolas during the talk, please put them in the chat or even unmute yourself at the end of the session and ask them directly. We started doing that from todays talk. Just to let you know, this video and all previous bytesize talks are on our youtube channel, so you can feel free to consult them there as well. All links are still on our homepage. With that, thanks for joining us again Nicolas and over to you."

Please also add a timestamp.

**Comment by FranBonath** [comment]
Hej @tommasianna, do you happen to have the PR number for the PR that solves this issue?

**Comment by tommasianna** [comment]
Sorry, isn't it #1707 ?
