### ISSUE TITLE
Add Math support to the website

### ISSUE THREAD

**Issue by aidaanva** [nf-core/website#1784]
**Is your feature request related to a problem? Please describe.**
I am currently writing some documentation for nf-core/eager where I would like to include mathematical expressions, however after having asked in the slack channel the mathematical expression in Markdown support on Github is not currently working for the rendering of output.md on the nf-core website

**Describe the solution you'd like**
Add support for the rendering of mathematical expressions, such as [MathJax](https://www.mathjax.org/) used by Github 

**Describe alternatives you've considered**
@MatthiasZepper also suggested [Katex](https://katex.org/), potentially more performant than MathJax

**Additional context**
A discussion took place in the slack channel on the [2th of June 2023](https://nfcore.slack.com/archives/CE7DN1U7M/p1685694670362699)

**Comment by mashehu** [comment]
done https://nf-co.re/docs/contributing/special_content#latex-formulas

**Comment by aidaanva** [comment]
Thank you!
