### ISSUE TITLE
update_module_details script and pipeline modules.json file format

### ISSUE THREAD

**Issue by gq1** [nf-core/website#1821]
the pipeline modules.json file has new format now. 

For example, [viralrecon](https://github.com/nf-core/viralintegration/blob/7e6316328e0d163e9a08ee1cee2be370180fd530/modules.json#L4-L12):

```json
    "repos": {
        "https://github.com/nf-core/modules.git": {
            "modules": {
                "nf-core": {
                    "custom/dumpsoftwareversions": {
                        "branch": "master",
                        "git_sha": "c8e35eb2055c099720a75538d1b8adb3fb5a464c",
                        "installed_by": ["modules"]
                    },
```

It seems the `update_module_details.php` script hasn't been updated yet.

https://github.com/nf-core/nf-co.re/blob/4d2ac445da4072a953685568bc25eb3f9a431991/update_module_details.php#L370

**Comment by mashehu** [comment]
this script has been replaced by https://github.com/nf-core/website/blob/main/bin/components.json.js in the website rewrite
