### ISSUE TITLE
SQL query in script update_stats.php

### ISSUE THREAD

**Issue by gq1** [nf-core/website#1822]
It seems this part code does nothing except throwing an error.

https://github.com/nf-core/website/blob/4d2ac445da4072a953685568bc25eb3f9a431991/update_stats.php#L166-L168

**Comment by ewels** [comment]
Not quite - that part of the code executes the SQL query that was prepared in the code block above it (to insert GitHub pipeline contribution statistics). Without it, the query string would be prepared but never actually submitted to the database.

Could you elaborate on what the error is, and where you're seeing it?

**Comment by gq1** [comment]
I never write any php code, just read and try to understand it. This block is doing the final database commit things?

Here is the error message.
`ERROR: Could not execute INSERT INTO github_pipeline_contrib_stats (pipeline_id, author, avatar_url, week_date, week_additions, week_deletions, week_commits) VALUES (?, ?, ?, ?, ?, ?, ?). You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?, ?, ?, ?, ?, ?, ?)' at line 1`

If I remove this block, and clear all the tables, re-run the script, the data seems saved correctly.

**Comment by ewels** [comment]
Yup, `mysqli_prepare()` is used to prepare the SQL statement in a safe manner (eg. no SQL injection attacks) and the `mysqli_query()` function executes it.

The error just means that something is going wrong with the entire code block. I'm not really sure why, it doesn't elaborate much. The code seems to work fine on the live server.

All of the PHP code is now depreciated and will soon be rewritten / removed, so it's not really worth worrying about at this point. The main site rewrite went live today, stats is still using the old site but it should hopefully be rewritten as well before long.
