### ISSUE TITLE
Installation page is broken

### ISSUE THREAD

**Issue by bounlu** [nf-core/website#1853]
Page is broken:
https://nf-co.re/usage/installation

**Comment by mashehu** [comment]
You need to have a slash in the end: https://nf-co.re/docs/usage/installation/
Where did you find the above link?

**Comment by bounlu** [comment]
> You need to have a slash in the end: https://nf-co.re/docs/usage/installation/ Where did you find the above link?

I see. I got there when clicked the first link when I googled for "nf-core install".
