### ISSUE TITLE
Broken link to pipeline release checklist

### ISSUE THREAD

**Issue by jasmezz** [nf-core/website#1855]
**Describe the bug**
The link from the old website ([Release checklist](https://nf-co.re/docs/contributing/adding_pipelines/release_checklist/)) does not work anymore.

**To Reproduce**

1. Go to [Pipeline release docs](https://nf-co.re/docs/contributing/adding_pipelines/#making-the-first-release), scroll down to "Making the release" or just google the checklist
2. Click on link to release checklist
3. See 404 error

**Expected behavior**
Wrong link should be replaced with: https://nf-co.re/docs/contributing/release_checklist/

**Comment by mashehu** [comment]
Thanks. The link is https://nf-co.re/docs/contributing/release_checklist/, I am preparing a PR to fix the link in https://nf-co.re/docs/contributing/adding_pipelines/ (if it is where you stumbled over it.
