### ISSUE TITLE
Links to linting errors and warning descriptions are broken.

### ISSUE THREAD

**Issue by alxndrdiaz** [nf-core/website#1904]
**Describe the bug**
Links to linting errors and warning descriptions are broken.

**To Reproduce**

1. Run nf-core lint inside a pipeline repository.
2. Click on any link to an error or warning description such as ` files_exist:` or `nextflow_config:` (see screenshot below)-
3. Try to open the link in a browser.
4. See: "Error 404: Page Not Found".

**Expected behavior**

**Screenshots**

![image](https://github.com/nf-core/website/assets/32914813/f5c8901a-09a0-40be-b9fa-16551def46f9)

![image](https://github.com/nf-core/website/assets/32914813/7f6e38de-09a5-45ae-887f-6c9750d341f0)

**Browser (please complete the following information):**

- OS: Ubuntu 22.04.2 LTS
- Browser Mozilla Firefox
- Version 115.0.2

**Additional context**
Only observed with Mozilla Firefox.

**Comment by mashehu** [comment]
Should be fixed now. Can you please check again?

**Comment by alxndrdiaz** [comment]
@mashehu It is working now.
