### ISSUE TITLE
Example site is left in the contribution docs

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/website#1908]
Hey! Looks like a test/example site is left in the contribution docs: https://nf-co.re/docs/contributing/special_content

![image](https://github.com/nf-core/website/assets/12273093/f84bea90-e0ad-48ce-9fb7-66706a2ebb2d)

**Comment by mashehu** [comment]
I thought it might be useful to point to this page for people asking about our syntax for admonitions, mermaid graphs and formulas. Maybe needs more text?

**Comment by FriederikeHanssen** [comment]
ah that makes sense. Maybe a titel/section: "Contributing to the website" or something along that line would have made it clearer for me :)

**Comment by mashehu** [comment]
I added a short intro to the whole page: https://github.com/nf-core/website/pull/1915
