### ISSUE TITLE
Astro 3.0

### ISSUE THREAD

**Issue by Emiller88** [nf-core/website#1960]
https://astro.build/blog/astro-3/
https://docs.astro.build/en/guides/upgrade-to/v3/

**Comment by mashehu** [comment]
any timeline on this? 🙂

**Comment by Emiller88** [comment]
Went on Vacation 😆 Thanks for throwing down the gauntlet!

https://github.com/astro-community/md/issues/7

**Comment by mashehu** [comment]
We are quite heavily depending on remark and rehype plug-ins, so can't really use marked-based or similar libraries.
