### ISSUE TITLE
Results from AWS megatests not working correctly for versions older than the most recent one

### ISSUE THREAD

**Issue by FriederikeHanssen** [nf-core/website#1964]
**Describe the bug**
When trying to inspect files from the megatests using Firefox, I loop back to the beginning. See attached video. The same works perfectly fine on chrome.

**To Reproduce**

as example here I used https://nf-co.re/sarek/3.2.3/results/sarek/results-ed1cc8499366dcefea216fe37e36c6189537d57b/ and then `somatic_test /variant_calling/controlfreec/HCC1395T_vs_HCC1395N` and tried to inspect one of the pngs

**Expected behavior**

Display the png as it does when using Chrome. 

**Screenshots**
https://github.com/nf-core/website/assets/12273093/1ec1d803-bb2d-4867-81e3-83f65bf76d55

**Browser (please complete the following information):**

- OS: MacOS
- Browser Firefox
- Version 117.0

**Comment by mashehu** [comment]
Actually seems to be a different bug:
somehow the url is not updated when looking at the aws results for versions of the pipeline older than the most recent one. My current guess is that it is faulty redirects.
