### ISSUE TITLE
New pipeline release (tag) not available on website 

### ISSUE THREAD

**Issue by christopher-mohr** [nf-core/website#1967]
**Describe the bug**
 The new release [1.2.0](https://github.com/nf-core/nanostring/releases/tag/1.2.0) of the pipeline nf-core/nanostring does not show up on the respective pipeline page on the website. 

The page still shows tag `1.1.1` as most recent. On the [release stats page](https://nf-co.re/nanostring/releases_stats/) the release notes of the new release are displayed under the old release tag `1.1.1`.

**To Reproduce**

1. Go to '[the pipeline release stats page](https://nf-co.re/nanostring/releases_stats/)'

**Expected behavior**
I would expect to see the most recent release (tag) with the corresponding release notes.

**Screenshots**
<img width="904" alt="pipeline_release_issue" src="https://github.com/nf-core/website/assets/6513088/79e3bc98-6567-43ee-96fe-5a70da25acfd">

**Browser (please complete the following information):**

- OS: Windows 10 Enterprise
- Browser: Microsoft Edge
- Version: `116.0.1938.69`

**Additional context**

**Comment by mashehu** [comment]
Was a problem with the build script for pipeline.json. Should be fixed now.
