### ISSUE TITLE
Create a "latest" link for pipelines

### ISSUE THREAD

**Issue by Emiller88** [nf-core/website#2051]
GitHub has support for the "latest" release

For example: https://github.com/nf-core/methylseq/releases/latest
Redirects to 2.5.0(At the time of writing this)

I'd like to be able to do https://nf-co.re/methylseq/latest. I think https://nf-co.re/methylseq does this however.

But I'd like to be able to point to https://nf-co.re/methylseq/latest/docs/output.

So I don't forget to update it in `multiqc_config.yml` on release 🙃

**Comment by Emiller88** [comment]
Wait maybe that already works 🤔

**Comment by mashehu** [comment]
Yep, this is already there
