### ISSUE TITLE
404 error for https://nf-co.re/blog/2024/tools-2_13

### ISSUE THREAD

**Issue by heuermh** [nf-core/website#2310]
**Describe the bug**

From the release email **[nf-core/tools] Release 2.13 - v2.13 - Tin Puppy**

> Check the [nf-core blog post](https://nf-co.re/blog/2024/tools-2_13) for more information!

The url https://nf-co.re/blog/2024/tools-2_13 currently returns a 404 error.

**Comment by mashehu** [comment]
build wasn't finished yet, it's there now.

**Comment by heuermh** [comment]
Woot!  Thanks 😁
