### ISSUE TITLE
Error 404: the link referring to the documentation on how to customize snpEff and VEP annotations is broken

### ISSUE THREAD

**Issue by JC-Delmas** [nf-core/website#2312]
Hello,

Path provided with SnpEff cache is invalid.                                                            │
Please refer to https://nf-co.re/sarek/docs/usage/#how-to-customise-snpeff-and-vep-annotation for more information.    

![image](https://github.com/nf-core/website/assets/130393309/f51546af-0c64-452a-b150-6e832ef3b7ec)

**Comment by mashehu** [comment]
thanks for reporting this. the correct link is https://nf-co.re/sarek/3.4.0/docs/usage#how-to-customise-snpeff-and-vep-annotation I will try to implement a redirect

**Comment by JC-Delmas** [comment]
Thank you !
