### ISSUE TITLE
Port pipeline-health page from old site

### ISSUE THREAD

**Issue by mashehu** [nf-core/website#2361]
This page currently lives at https://oldsite.nf-co.re/pipeline_health and is built from https://github.com/nf-core/website/blob/old-site/public_html/pipeline_health.php 

We should move the backend stuff over to https://github.com/nf-core/website/blob/main/bin/pipelines.json.js and build a simple page, which renders the information from the json file.
```[tasklist]
### Tasks
- [ ] add needed info to pipelines.json
- [ ] add asstro page to render info
```

**Comment by alvaromartmart** [comment]
might be interested in taking a stab at this 👀

**Comment by mashehu** [comment]
sure, don't be overwhelmed by this, we gather quite a bit of data here. shout if something is unclear and we can discuss on gather or slack.
