### ISSUE TITLE
GitHub style admonitions not rendering

### ISSUE THREAD

**Issue by ewels** [nf-core/website#2409]
Looks like GitHub-style admonitions [such as this one](https://nf-co.re/tools#creating-a-new-pipeline) are not rendering nicely:

![CleanShot 2024-03-26 at 12 50 14@2x](https://github.com/nf-core/website/assets/465550/fae52571-9fb3-4296-baa2-b2fc4c4baffd)

I thought that we had implemented this at some point, so maybe a regression?

Would be good to [document this style](https://nf-co.re/docs/contributing/website_markdown) as well and say that it's good for GitHub readmes.

**Comment by mashehu** [comment]
forgot to add that specific type: https://github.com/nf-core/website/blob/main/src/components/octokit.js#L83
