### ISSUE TITLE
[404] Page not found: https://nf-co.re/docs/nf-core-tools/api_reference/2.14.1/pipeline_lint_tests

### ISSUE THREAD

**Issue by wjlim** [nf-core/website#2576]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser (please complete the following information):**

**Additional context**

**Comment by awgymer** [comment]
This issue also affects `module_lint_tests`.

To reproduce:

- Navigate to https://nf-co.re/docs/nf-core-tools/api_reference/2.14.1/module_lint_tests
- Click a link in the main section of the index page e.g. `main_nf`


Note that the sidebar links to the same pages work as expected. i.e. the actual link https://nf-co.re/docs/nf-core-tools/api_reference/2.14.1/module_lint_tests/main_nf works as expected. 

The issue appears to be a bad link generation in the main index page.
