### ISSUE TITLE
How to join nf-core slack?

### ISSUE THREAD

**Issue by apsteinberg** [nf-core/website#2597]
**Describe the bug**
I'm having trouble getting an invite to the nf-core Slack channel via the nf-co.re website.

**To Reproduce**

1. Go to '[https://nf-co.re/join](https://nf-co.re/join)'
2. Click on 'get an invite to nf-core Slack'
3. This yields a "This link is no longer active" message.

**Expected behavior**
I was expecting some instructions on how I could join. :)

**Screenshots**
Screenshot of message below:
<img width="800" alt="Screenshot 2024-06-30 at 3 20 20 PM" src="https://github.com/nf-core/website/assets/63111464/442d9f6f-4e3d-417f-bb5d-1627b254d691">

**Browser (please complete the following information):**

- OS: Mac Sonoma
- Browser Chrome

**Comment by ewels** [comment]
Hi @apsteinberg,

Apologies, we're having some issues updating the website but should get it fixed within a few hours.

In the mean time, here's a link that should work:

https://join.slack.com/t/nfcore/shared_invite/zt-2gkgdsy8z-DPRHZpNKnH6g_oX_cuupog

Phil
