### ISSUE TITLE
[404] Page not found: https://nf-co.re/hic/2.1.0/

### ISSUE THREAD

**Issue by fchuffar** [nf-core/website#2613]
**Describe the bug**

On this page : https://nf-co.re/hic/2.1.0/

there is dead link: https://nf-co.re/docs/usage/installation

**To Reproduce**

1. Go to https://nf-co.re/hic/2.1.0/
2. Click on *please refer to [this page](https://nf-co.re/docs/usage/installation) on how to*

**Comment by mashehu** [comment]
This should be fixed now. thanks for reporting
