### ISSUE TITLE
[404] Page not found: https://nf-co.re/atacseq/2.1.2/

### ISSUE THREAD

**Issue by EricTorralba** [nf-core/website#2619]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser (please complete the following information):**

**Additional context**

**Comment by maxulysse** [comment]
@EricTorralba Can you give more details?
I have no 404 errors on https://nf-co.re/atacseq/2.1.2/

**Comment by EricTorralba** [comment]
https://nf-co.re/atacseq/docs/usage#introduction

**Comment by mashehu** [comment]
thanks for the clarification. working on a fix
