### ISSUE TITLE
Highlight that **Everyone is welcome!** to contribute to discussions or code

### ISSUE THREAD

**Issue by d4straub** [nf-core/website#2657]
**Is your feature request related to a problem? Please describe.**

First of all I think the nf-core website is great and holds a lot of informative and important content. Thanks to all people working on it! However, I believe I found an issue:

A group that performed benchmarks made well-informed changes to a nf-core pipeline in a fork and asked us/me whether we/I can bring the changes to the nf-core pipeline. I asked why they weren't contributing directly to the pipeline, and the answer was "we were under the impression that nf-core does not encourage everyone to contribute here". As far as I understand nf-core, we welcome everyone to contribute.

I thought that it should have been obvious from the website that nf-core welcomes everyone to contribute. So I went to the nf-core website and was looking for a big welcome to soon-to-be contributors, but failed. I also discussed this in slack ([link](https://nfcore.slack.com/archives/C04QR0T3G3H/p1721308325004069) & following) and there seemed to me an agreement that the website is indeed not explicitly welcoming. There are places where interested people/developers are addressed, and those appear to rather highlight barriers and restrictions instead of encourage people to contribute.

For example:
![image](https://github.com/user-attachments/assets/9894f400-7347-4fd4-aeb8-bacecec35cfc)
The first box mentions new pipelines and that anyone has to speak with us before doing anything. The second box demands templates. The third box even highlights that we do _not allow_ stuff. I mean all those rules are fine, but at that point I dont see any explicit "welcome" and its actually rather exclusive, defensive, restrictive, instead of inclusive, in my opinion.

The "Join nf-core" part is hidden and also not explicitly stating that everyone may contribute, additionally, it lists a lot of stuff that is helpful but not required, if I am not mistaken. That doesn't make it easier for someone to join, I think.

Additionally, to me, there seems to be plenty of information about new pipelines, but not much for people that contribute smaller parts, i.e. want to add a module/feature to a pipeline. But I assume that new contributors typically are interested in smaller additions rather than complete pipelines.

**Describe the solution you'd like**

I would like to see something like

> Welcome, whoever you are, YOU can contribute here!
> Everyone is welcome to contribute, in any way! Contribute ideas and code directly via github or come talk to us in slack

or such. My idea is to show clearly and explicitly that everyone can contribute and via several channels without any preparations or blockages in their way. If there are prerequisites (e.g. joining github), those need to be listed, but requirements and optional stuff should be separated that the barrier is as low as possible. And only _after_ the "welcome!", restrictions and the like should be described, in my opinion.

Additionally, it might be nice to have not only descriptions of pipeline file structures and such but also a very small section, or a sentence, just saying that small changes/adjustments/improvements or just discussions and ideas are welcome, not just complete pipelines.

**Describe alternatives you've considered**

I dont really see an alternative than doing that on the website.

**Comment by ewels** [comment]
Agree that we could improve this.

The section of your screenshot was added because we had a lot of people turning up with completely written pipelines that we would then have to turn away because of overlap with existing pipelines / not using the template etc. So we wanted to push people to engage as early as possible.

I like your idea of highlighting that there are many ways to contribute (this wasn't the case when most of the homepage was written). My suggestion is that we have a new docs page called "how to get involved" or similar with brief descriptions of the different types of contributions. Then have a new band on the homepage saying "welcome to everyone" with a couple of very brief examples and linking to the docs page for more detail. The homepage band should come pretty high up / have quite high priority.

**Comment by ewels** [comment]
Related: https://github.com/nf-core/website/issues/1422

**Comment by ewels** [comment]
Ok, had a stab at addressing this strip on the homepage in https://github.com/nf-core/website/pull/2721:

![CleanShot 2024-09-19 at 01 26 21@2x](https://github.com/user-attachments/assets/ae394434-d983-437d-9fdc-80ba41b3df3d)

Hopefully a bit friendlier now, even if the general points are the same. I added your suggested lead text above there to encourage anyone to get involved.

Shout if you think that it should have any tweaks, thanks for the suggestion @d4straub!

**Comment by ewels** [comment]
Note that @christopher-hakkaart is working on new and improved "Getting started" docs, I'd be very open to having something on the homepage linking into those when they're ready. We can revisit then if so.

**Comment by d4straub** [comment]
Thanks, I also think that is a much more welcoming message and sounds much less barrier-heavy! The point that is in my opinion not perfectly addressed are smaller contributions. Smaller contributions are addressed in the headline, but not int he three boxes below ("Develop with the community" sound like ti, but then it highlights proposing _a whole pipeline as a first step_ [who is doing that????], not contributing a code snippet). But if there is a "Getting started" docs that will not _start_ directly with suggesting someone has to come with a whole new pipeline (idea), than thats covered I think. Thanks again!
