### ISSUE TITLE
Starting with a DSL2 Pipeline Tutorial

### ISSUE THREAD

**Issue by jfy133** [nf-core/website#887]
**Is your feature request related to a problem? Please describe.**
With the full speed-ahead on adoption of DSL2, quite a few people are pretty lost how to start with the relatively complex (but powerful) nf-core DSL2 template. 

**Describe the solution you'd like**
A few people have requested on slack a 'getting started with DSL2 pipeline documentation/tutorial'. This should be done at some point.

**Comment by sateeshperi** [comment]
[nf-core/variantcall](https://sateeshperi.github.io/nextflow_varcal/nextflow/nextflow_nfcore_variantcall)
